### ISSUE TITLE
Social Media Links Missing

### ISSUE THREAD

**Issue by Creesh-Design** [Xirdion/contao-author-bundle#10]
Under Contao 4.9.12 there are no fields for social media.

https://share.getcloudapp.com/bLuKk24l

**Comment by Xirdion** [comment]
Hi there. Thanks for your input.
First of all I would recommend to upgrade to the newest Contao 4.9.* release as 4.9.12 is already outdated.
Further more I could no reproduce the error. All fields are always available in the back end.
Maybe you did not set the correct user rights?
