### ISSUE TITLE
Update extension name in readme + abandoned hint

### ISSUE THREAD

**Issue by rabauss** [Xirdion/contao-author-bundle#12]
The renaming is not correctly solved - here:
https://github.com/Xirdion/contao-author-bundle/blob/b8672578c391037869c496129843b02e09edbb4e/README.md?plain=1#L7

Also here:
https://github.com/Xirdion/contao-author-bundle/blob/b8672578c391037869c496129843b02e09edbb4e/composer.json#L13
and the link in all headers 😉 

Can you please update the abandoned hint for `dreibein/contao-author-bundle` ? 
Unfortunately, the `sowieso/contao-author-bundle` was removed instead of setting it abondoned 😞 
https://packagist.org/packages/dreibein/contao-author-bundle

**Comment by Xirdion** [comment]
Hi @rabauss 
thanks for the information.
I updated the files to improve the renaming of the bundle.
Unfortunately I did not found a way to update the abandoned hint for `dreibein/contao-author-bundle`.
Every change would just be applied to the `xirdion/contao-author-bundle`. :(

**Comment by rabauss** [comment]
The hint to `xirdion/contao-author-bundle` needs to be updated on packagist in the `dreibein/contao-author-bundle` from the vendor of this package!

**Comment by rabauss** [comment]
@Xirdion I'm really sorry, but the current Version `>= 2.0.1` is not usable anymore.
Because not all Namespaces of `Sowieso` where correctly changed especially in the `listener.yaml` and in the Tests!
https://github.com/Xirdion/contao-author-bundle/search?q=Sowieso

**Comment by Xirdion** [comment]
Hi @rabauss.
Thank you very much. With version `2.0.6` the Namespaces and tests are now correct.
Unfortunately there is no dreibein vendor for packagist. So I think the package information wont be changed anymore.
